# Generated by Django 5.0.4 on 2024-05-25 07:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_salle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacited', models.IntegerField(default=35)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=150)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id_class_session', models.AutoField(primary_key=True, serialize=False)),
                ('heureDebut', models.TimeField(blank=True, null=True)),
                ('heureFin', models.TimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_app.classroom')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assoc', models.DateField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idStudent', models.AutoField(primary_key=True, serialize=False)),
                ('codeMassar', models.CharField(max_length=100, unique=True)),
                ('dateNaissance', models.DateField()),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('groups', models.ManyToManyField(related_name='students', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='student_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id_marking', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('date_marked', models.DateField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.classsession')),
                ('code_massar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
